# Generated by Django 2.0.7 on 2018-07-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
